DSC_Disk: Add dev drive creation support to disk resource
dsccommunity/StorageDsc pull request #278
Opened 2023-09-22 21:43 UTC by bbonaby

#### Pull Request (PR) description

This PR adds Dev Drive creation support and the ability to explicitly use unallocated space to create a new partition even when there is a partition with the same size as the one the user enters in.

#### This Pull Request (PR) fixes the following issues

- Fixes #276

#### Task list

- [ x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ x] Resource documentation added/updated in README.md.
- [ x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ x] Comment-based help added/updated.
- [x ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2023-09-25 05:33 UTC, PlagueHO reviewed
Thanks @bbonaby - I'll get onto review this week. Looks like the HQRM tests are failing:

https://dev.azure.com/dsccommunity/StorageDsc/_build/results?buildId=8172&view=logs&j=47266b63-9d03-5281-d38b-75133a4264f6&t=4d8b314c-6b76-5ae4-aed5-2779b7a3afdb&l=1019

They are just style corrections in StorageDsc.Common.psm1 - nothing major and should be a quick fix.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-:-Nf9oFmNEyZIcuA97g_i:b-9044k5)* status: 0 of 9 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-02 23:37 UTC, bbonaby commented
@PlagueHO any update on this and #279 ?

2023-10-03 07:37 UTC, PlagueHO requested changes
Sorry about the delay.

Can we add some notes (and links) about how Dev Drive should be used in the README.md for Disk? E.g. in here: [StorageDsc/source/DSCResources/DSC\_Disk/README.md at main · dsccommunity/StorageDsc (github.com)](https://github.com/dsccommunity/StorageDsc/blob/main/source/DSCResources/DSC_Disk/README.md)

Could we include:
- is it possible to have more than one Dev Drive in a machine and if not, what will happen if more than one volume is defined as a Dev Drive? Looking at example, it does seem like more than one DevDrive can be mounted.
- what happens if a volume that was assigned as a Dev Drive is changed to no longer being a Dev Drive - e.g. can the resource turn a Dev Drive back into a normal drive/volume (required to be idempotent). If not, then we'd need to document this as there will be situations where this resource won't be able to bring the disk into desired state. Ideally, we always want a resource to be able to go from any state into the desired state - but sometimes this isn't possible - so we need to indicate this. Looking at the code, it does look like once a volume is defined as a DevDrive, it isn't possible to bring it into a new state - is my understanding correct?
- What would happen if DevDrive feature isn't enabled on a machine and DevDrive is requested? 

> Reviewed 4 of 9 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-:-NfoARNS7E8o6uTin4Dw:b-lliqss)* status: 7 of 9 files reviewed, 18 unresolved discussions (waiting on @bbonaby)

___
*[`CHANGELOG.md` line 8 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nfo9nA2EUTWib8mNq-k:-Nfo9nA2EUTWib8mNq-l:b-a3d9vk) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/CHANGELOG.md#L8)):*
> ```Markdown
> ## [Unreleased]
> 
> - Updated DSC_Disk to allow volumes to be formatted as Dev Drives:  Fixes #276
> ```

For consistency, can you use this format?



_Suggestion:_
```Markdown
- Updated DSC_Disk to allow volumes to be formatted as Dev Drives - Fixes [Issue #276](https://github.com/dsccommunity/StorageDsc/issues/276)
```
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 181 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoC2Bc0kFOPySP8XiE:-NfoC2Bc0kFOPySP8XiF:b-j4moaw) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L181)):*
> ```PowerShell
> 
>     .PARAMETER UseUnallocatedSpace
>         Specifies that a new partition and volume should be formatted onto unallocated space on the disk.
> ```

Does this parameter differ from the _Size_ parameter being left empty above? This automatically forces the disk to use all remaining unallocated space for the volume.

I think I might be getting confused though (after looking at the example) - aren't volumes & partitions going to be always created using unallocated space?

I guess what I'm asking is: is this parameter needed?
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 415 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoEYjV98Qr-5_E--mO:-NfoEYjV98Qr-5_E--mP:bo15em8) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L415)):*
> ```PowerShell
>             There are two instances when we attempt to create a new partition:
>             1. When there are no partitions matching the drive letter the user entered.
>             2. When the user has advised us that they want to create a new partition on the disk's
> ```

If `$Size` is not specified and there is no matching partition found and empty space then `$partition` should be null, so I think (I could be wrong) that `$UseUnallocatedSpace` isn't needed? 
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 584 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoFEKND0LLc1Cex--Y:-NfoFEKND0LLc1Cex--Z:baa6qzd) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L584)):*
> ```PowerShell
>         if ($DevDrive)
>         {
>             $formatVolumeParameters['DevDrive'] = $DevDrive
> ```

We can't assume that Test has fired, so can we also assert the DevDrive requirements here?
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 626 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoFhtTBdARExxck4cH:-NfoFhtTBdARExxck4cI:baa6qzd) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L626)):*
> ```PowerShell
>                     if ($PSBoundParameters.ContainsKey('DevDrive'))
>                     {
>                         $formatParam.Add('DevDrive', $DevDrive)
> ```

We can't assume that Test has fired, so can we also assert the DevDrive requirements here?
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 796 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoGO0h5ET71py6IYYH:-NfoGO0h5ET71py6IYYI:bp1z5h8) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L796)):*
> ```PowerShell
>     } # if
> 
>     # Check Dev Drive feature is enabled and that the user inputted ReFS as the file system.
> ```

This block should be down further as it will fail if the disk isn't yet initialized. 

It also looks like it sort of duplicates some of the code/checks from the code following (e.g., from about here onwards: [StorageDsc/source/DSCResources/DSC\_Disk/DSC\_Disk.psm1 at main · dsccommunity/StorageDsc (github.com)](https://github.com/dsccommunity/StorageDsc/blob/main/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L795))

E.g., right now there are two free space size checks performed if a DevDrive is used - one check here and another on line [StorageDsc/source/DSCResources/DSC\_Disk/DSC\_Disk.psm1 at main · dsccommunity/StorageDsc (github.com)](https://github.com/dsccommunity/StorageDsc/blob/main/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L812)

Can this code be merged together to reduce duplicate functionality?
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 809 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoGjx342TYLtLPaopj:-NfoGjx342TYLtLPaopk:bs9awmd) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L809)):*
> ```PowerShell
>         if ($disk.PartitionStyle -ne 'RAW' )
>         {
>             $currentDiskFreeSpace = $disk.LargestFreeExtent
> ```

This is interesting: we are using the `Get-PartitionSupportedSize` to get the largest free extent value, but it's pretty flaky. So perhaps it would be better to convert to using disk.LargestFreeExtent?
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.schema.mof` line 16 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoI6Yt9Tj7Df86qgD0:-NfoI6Yt9Tj7Df86qgD1:bkls66f) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.schema.mof#L16)):*
> ```
>     [Write, Description("Specifies if the disks partition schema should be removed entirely, even if data and OEM partitions are present. Only possible with AllowDestructive enabled.")] Boolean ClearDisk;
>     [Write, Description("Specifies if the volume should be formatted as a Dev Drive.")] Boolean DevDrive;
>     [Write, Description("Specifies that a new partition and volume should be formatted onto unallocated space in the disk.")] Boolean UseUnallocatedSpace;
> ```

See previous comments - how does this differ from when size parameter is not specified?
___
*[`source/Examples/Resources/Disk/3-Disk_InitializeDiskWithADevDrive.ps1` line 22 at r2](https://reviewab [...]

2023-10-03 07:37 UTC, PlagueHO reviewed
Also - thank you for submitting this and sorry about taking so long :D

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-:-NfoT75lDEP-leb5e6Bh:b-c4aat2)* status: 7 of 9 files reviewed, 18 unresolved discussions (waiting on @bbonaby)



<!-- Sent from Reviewable.io -->

2023-10-04 01:26 UTC, bbonaby commented
Thanks @PlagueHO  I'll update the PR based on your suggestions

2023-10-04 03:17 UTC, bbonaby reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/278)* status: 7 of 9 files reviewed, 18 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 8 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nfo9nA2EUTWib8mNq-k:-NfsfGed1389M4ODx0-V:b-qoelh7) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/CHANGELOG.md#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

For consistency, can you use this format?
</blockquote></details>

thanks will update
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 181 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoC2Bc0kFOPySP8XiE:-NfsKzJK9hzdFLG4Nk7o:b-w63n14) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L181)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Does this parameter differ from the _Size_ parameter being left empty above? This automatically forces the disk to use all remaining unallocated space for the volume.

I think I might be getting confused though (after looking at the example) - aren't volumes & partitions going to be always created using unallocated space?

I guess what I'm asking is: is this parameter needed?
</blockquote></details>

So, the issue here is when the user wants to use a specific size, and not use all the remaining unallocated space when there is an existing volume on the disk, that is the same size as what the user enters in. Correct me if I'm wrong because I may have misunderstood, but I believe in this case, the Disk resource would actually use that same volume it found that matches the users size. To prevent this from happening that's what the use allocated space flag would be for. 
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 415 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoEYjV98Qr-5_E--mO:-NfsMyBd-I9qSAsPaaS0:b-9zxq5j) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L415)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

If `$Size` is not specified and there is no matching partition found and empty space then `$partition` should be null, so I think (I could be wrong) that `$UseUnallocatedSpace` isn't needed?
</blockquote></details>

So the case for the `UseUnallocatedSpace` flag would be for when the size is specified. The problem is actually stemming from source/DSCResources/DSC_Disk/DSC_Disk.psm1:348, the Disk resource changes the `$partition` value to match a partition that is the same size the user enters in. The user may not want to format the partition it finds, but instead only use unallocated space if there is any. Let me know if you think there is a better way to address this though. If I remember correctly that was the reason why I ended up adding this flag.


On a side note, ultimately what I would want is for the ability for the Disk resource to resize an existing volume to create enough unallocated space for a Dev Drive or any other kind of volume all in one go if needed, to create a new volume. Right now, in the Disk resource you'd have to specify the size you want a volume to be first, then actually create another volume using that new unallocated space. This means you have to know the initial size of the first volume. E.g if My C drive was 200 Gb on disk 1 that has a max of 200 Gb and I want to create another volume that's 50 Gb on the same disk. In a config file I'd first have to tell the Disk resource that I want my C drive to be 150 Gb. Then separately in the config file use the Disk resource again to create a new volume that's 50 Gb using this newly unallocated space. Instead, I'd just want to only use the Disk resource once in a config file to create a new volume on a specific disk. The Disk resource would then resize an existing volume internally to create this new volume if it isn't already created. This way the user wouldn't have to know the size of the volume that will be resized, they can just expect that a volume of their specified size and parameters will be created if it isn't created already. I was thinking this would be a separate PR to add this functionality in.
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 584 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoFEKND0LLc1Cex--Y:-NfsYZb-61mQ5cqmqWaX:b-6u6wc2) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L584)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

We can't assume that Test has fired, so can we also assert the DevDrive requirements here?
</blockquote></details>

alright will update this thanks
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 626 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoFhtTBdARExxck4cH:-NfsYbFY8-nf2HdeVDkZ:b-6u6wc2) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L626)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

We can't assume that Test has fired, so can we also assert the DevDrive requirements here?
</blockquote></details>

alright will update this thanks
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 796 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoGO0h5ET71py6IYYH:-NfsYzJM1-8LVQE7OWE4:b-sn4kh0) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L796)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This block should be down further as it will fail if the disk isn't yet initialized. 

It also looks like it sort of duplicates some of the code/checks from the code following (e.g., from about here onwards: [StorageDsc/source/DSCResources/DSC\_Disk/DSC\_Disk.psm1 at main · dsccommunity/StorageDsc (github.com)](https://github.com/dsccommunity/StorageDsc/blob/main/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L795))

E.g., right now there are two free space size checks performed if a DevDrive is used - one check here and another on line [StorageDsc/source/DSCResources/DSC\_Disk/DSC\_Disk.psm1 at main · dsccommunity/StorageDsc (github.com)](https://github.com/dsccommunity/StorageDsc/blob/main/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L812)

Can this code be merged together to reduce duplicate functionality?
</blockquote></details>

Hmm the only difference here I guess is that Dev Drive have to be 50 Gb or more. The  `Assert-DiskHasEnoughSpaceToCreateDevDrive ` check below is really to confirm that the user has enough space to create one and if not we throw. But actually for uninitialized disks, do you mean ones with out a partition style? I updated the check to include the check for the partition style last week and the check now works for uninitialized disks. But I don't mind moving it down if you still want me to. I think the place where you outlined only hits when we find a partition with the user inputted drive letter, while this one checks both I believe. I'll try taking a crack at moving lines 

1. source/DSCResources/DSC_Disk/DSC_Disk.psm1:802
2. through 
3. source/DSCResources/DSC_Disk/DSC_Disk.psm1:827

down and see if I can merge the two.
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 809 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoGjx342TYLtLPaopj:-NfsbPa2ESEapxtoVaDE:b-f8rveq) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f0 [...]

2023-10-12 22:23 UTC, PlagueHO commented
Sorry about the delay @bbonaby - I'll get back to your comments in the weekend.

2023-10-13 19:45 UTC, bbonaby commented
Hey @PlagueHO  I plan on updating this PR today. If possible would you be able to hold off until I update it? I've gotten rid of the 'UseUnallocatedSpace' and would like you to take a look at a different approach I did without needing that flag. Thanks

2023-10-14 08:44 UTC, bbonaby reviewed
I updated the PR, we should be good to go for another round of review. This time I added alot more details and comments explaining the usage. I also updated the disk resource description with how the resource works with the Dev Drive flag. I reworked it so we automatically will resize a partition on the disk should we need more space to create the Dev Drive volume. I also added in the Description for the disk dsc that we don't have integration tests for the Dev Drive flag as its not available in server 2019 and server 2022. So I had to test the scenarios manually, which is where I found an existing bug in in dsc resource that actually formatted one of my partitions unnecessary :( , but I fixed it and added a comment in the latest commit.  

> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-:-NghFNpO17vGn-3SjxCd:btckild)* status: 2 of 12 files reviewed, 18 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 8 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nfo9nA2EUTWib8mNq-k:-NghGZA72PBHqEq9VS_a:b2amzql) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/CHANGELOG.md#L8)):*
<details><summary><i>Previously, bbonaby (bbonaby-MSFT) wrote…</i></summary><blockquote>

thanks will update
</blockquote></details>

Fixed in latest commit. Thanks.
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 181 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoC2Bc0kFOPySP8XiE:-NghGsnECLYcv7-OHTaS:b4krc6u) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L181)):*
<details><summary><i>Previously, bbonaby (bbonaby-MSFT) wrote…</i></summary><blockquote>

So, the issue here is when the user wants to use a specific size, and not use all the remaining unallocated space when there is an existing volume on the disk, that is the same size as what the user enters in. Correct me if I'm wrong because I may have misunderstood, but I believe in this case, the Disk resource would actually use that same volume it found that matches the users size. To prevent this from happening that's what the use allocated space flag would be for.
</blockquote></details>

I removed the parameter in the latest commit as its no longer needed. Thanks
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 415 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoEYjV98Qr-5_E--mO:-NghH0UWDnK229pcgtlK:b-pjhtss) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L415)):*
<details><summary><i>Previously, bbonaby (bbonaby-MSFT) wrote…</i></summary><blockquote>

So the case for the `UseUnallocatedSpace` flag would be for when the size is specified. The problem is actually stemming from source/DSCResources/DSC_Disk/DSC_Disk.psm1:348, the Disk resource changes the `$partition` value to match a partition that is the same size the user enters in. The user may not want to format the partition it finds, but instead only use unallocated space if there is any. Let me know if you think there is a better way to address this though. If I remember correctly that was the reason why I ended up adding this flag.


On a side note, ultimately what I would want is for the ability for the Disk resource to resize an existing volume to create enough unallocated space for a Dev Drive or any other kind of volume all in one go if needed, to create a new volume. Right now, in the Disk resource you'd have to specify the size you want a volume to be first, then actually create another volume using that new unallocated space. This means you have to know the initial size of the first volume. E.g if My C drive was 200 Gb on disk 1 that has a max of 200 Gb and I want to create another volume that's 50 Gb on the same disk. In a config file I'd first have to tell the Disk resource that I want my C drive to be 150 Gb. Then separately in the config file use the Disk resource again to create a new volume that's 50 Gb using this newly unallocated space. Instead, I'd just want to only use the Disk resource once in a config file to create a new volume on a specific disk. The Disk resource would then resize an existing volume internally to create this new volume if it isn't already created. This way the user wouldn't have to know the size of the volume that will be resized, they can just expect that a volume of their specified size and parameters will be created if it isn't created already. I was thinking this would be a separate PR to add this functionality in.
</blockquote></details>

I reworked how the functionality works when the Dev Drive flag is set to true. Now what I spoke about in paragraph 2 is reality with this latest commit. Thanks.
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 584 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoFEKND0LLc1Cex--Y:-NghHf-O0G4ABri8V0kt:bn2blff) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L584)):*
<details><summary><i>Previously, bbonaby (bbonaby-MSFT) wrote…</i></summary><blockquote>

alright will update this thanks
</blockquote></details>

updated, thanks.
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 626 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoFhtTBdARExxck4cH:-NghHgqI4gHD8LKuzOZG:bn2blff) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L626)):*
<details><summary><i>Previously, bbonaby (bbonaby-MSFT) wrote…</i></summary><blockquote>

alright will update this thanks
</blockquote></details>

updated, thanks.
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 796 at r2](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NfoGO0h5ET71py6IYYH:-NghHq_B1M8BmWAGBQQZ:bvivwcv) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/19a146f597c68c87bb84d8c2617ed92765f02675/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L796)):*
<details><summary><i>Previously, bbonaby (bbonaby-MSFT) wrote…</i></summary><blockquote>

Hmm the only difference here I guess is that Dev Drive have to be 50 Gb or more. The  `Assert-DiskHasEnoughSpaceToCreateDevDrive ` check below is really to confirm that the user has enough space to create one and if not we throw. But actually for uninitialized disks, do you mean ones with out a partition style? I updated the check to include the check for the partition style last week and the check now works for uninitialized disks. But I don't mind moving it down if you still want me to. I think the place where you outlined only hits when we find a partition with the user inputted drive letter, while this one checks both I believe. I'll try taking a crack at moving lines 

1. source/DSCResources/DSC_Disk/DSC_Disk.psm1:802
2. through 
3. source/DSCResources/DSC_Disk/DSC_Disk.psm1:827

down and see if I can merge the two.
</blockquote></details>

updated thanks. I removed that entire block and function. Instead I did what you suggested and did the checks closer to where the we create a new partition. That made it easier to just use Assert-SizeMeetsMinimumDevDriveRequirement and either the partition size , volume size, user inputted size and the  $disk.LargestFreeExtent sizes where appropriate.
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 725 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NghL9ZT9W2aTQOW6Rut:-NghL9ZT9W2aTQOW6Ruu:byvl783) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/d419000a2c1d4590b4cb18dd20575e565641a2d2/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L725)):*
> ```PowerShell
>     {
>         $partition = $assignedPartition
>     }
> ```

Fyi this is the bug I was talking about in another comment that ended u [...]

2023-10-23 20:05 UTC, bbonaby commented
@PlagueHO any update on this? Thanks

2023-10-24 05:25 UTC, PlagueHO commented
Hi @bbonaby - apologies, day job has been taking up all my bandwidth. Planning to have time for this tomorrow night.

2023-10-25 06:15 UTC, PlagueHO requested changes
Looking really awesome @bbonaby - just some super minor things and we can merge. Due to the small logic changes to Set/Test, I think it is worth marking this as a BREAKING CHANGE, just to bump the major version and avoid any configs unexpectedly breaking.

> Reviewed 4 of 11 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-:-Nh_T-k8-av3W-1eLBZj:bdtpwhi)* status: all files reviewed, 28 unresolved discussions (waiting on @bbonaby)

___
*[`CHANGELOG.md` line 8 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_NxU8-3DdoVrlOdG6:-Nh_NxU8-3DdoVrlOdG7:bgwkqek) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/CHANGELOG.md#L8)):*
> ```Markdown
> ## [Unreleased]
> 
> - Updated DSC_Disk to allow volumes to be formatted as Dev Drives - Fixes [Issue #276](https://github.com/dsccommunity/StorageDsc/issues/276)
> ```

I think we should make this a `BREAKING CHANGE:` just because it does change some existing behaviors that "could" break existing configs. This is fine though and will just bump major version to 6.

Also, can you add `### Added` before change line above (with a blank line before it). E.g.

```
### Added

- Disk:
  - BREAKING CHANGE: Added support for volumes to be formatted as Dev Drives - Fixes [Issue #276](https://github.com/dsccommunity/StorageDsc/issues/276)
```

___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 725 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-NghL9ZT9W2aTQOW6Rut:-Nh_NltpBBrARzB6CNPU:b-6j57et) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/d419000a2c1d4590b4cb18dd20575e565641a2d2/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L725)):*
<details><summary><i>Previously, bbonaby (bbonaby-MSFT) wrote…</i></summary><blockquote>

Fyi this is the bug I was talking about in another comment that ended up formatting one my unrelated partitions.  Its I fixed with this but let me know if you have any issues. thanks
</blockquote></details>

Good catch. We didn't used to consider running Set without Test, but this is required now. 
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 402 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_Dho86laaswdzJJ5R:-Nh_Dho86laaswdzJJ5S:b-qs2ddd) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L402)):*
> ```PowerShell
>                             $tempPartition.Type -eq 'Reserved' -or `
>                             $tempPartition.Type -eq 'Recovery' `
>                         )
> ```

Can this be?



_Suggestion:_
```PowerShell
                        $shouldNotBeResized = ($tempPartition.Type -in 'System','Reserved','Recovery')
```
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 416 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_E_5q8ScEjHF_P2-1:-Nh_E_5q8ScEjHF_P2-2:b-qq75tj) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L416)):*
> ```PowerShell
>                         Write-Verbose -Message ( @(
>                             "$($MyInvocation.MyCommand): "
>                             $($script:localizedData.CheckingIfPartitionCanBeResizedForDevDrive -F $tempPartition.DriveLetter)
> ```

nit: change to lower case `-f`
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 440 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_Ed5-0nMNLXFdHNUM:-Nh_Ed5-0nMNLXFdHNUN:b-qq75tj) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L440)):*
> ```PowerShell
>                             Write-Verbose -Message ( @(
>                                 "$($MyInvocation.MyCommand): "
>                                 $($script:localizedData.PartitionFoundThatCanBeResizedForDevDrive -F $tempPartition.DriveLetter)
> ```

nit: change to lower case `-f`
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 451 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_Ee69ErTr0U76atHT:-Nh_Ee69ErTr0U76atHU:b-qq75tj) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L451)):*
> ```PowerShell
>                         Write-Verbose -Message ( @(
>                             "$($MyInvocation.MyCommand): "
>                             $($script:localizedData.PartitionCantBeResizedForDevDrive -F $tempPartition.DriveLetter)
> ```

nit: change to lower case `-f`
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 460 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_EfEC4eG7WeXFB4JJ:-Nh_EfEC4eG7WeXFB4JK:b-qq75tj) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L460)):*
> ```PowerShell
>                     {
>                         $SizeInGb = [Math]::Round($Size / 1GB, 2)
>                         throw ($script:localizedData.FoundNoPartitionsThatCanResizedForDevDrive -F $SizeInGb)
> ```

nit: change to lower case `-f`
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 465 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_FrsX7iKcES41Ei3h:-Nh_Frs_2EnTuNuPilVb:b-97ndey) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L465)):*
> ```PowerShell
>                 else
>                 {
>                     # Find the first basic partition matching the size
> ```

nit: to make tracing this code easier can you add to this comment that this is "when not a DevDrive"?
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 731 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_NLEqBxH9CRUMiP74:-Nh_NLEu-Kis_YyW5Ich:br0qt4y) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L731)):*
> ```PowerShell
> 
>     <#
>         If the Set-TargetResource function is run as a standalone function, and $assignedPartition is not null and there are multiple partitions in $partition,
> ```

nit: Can you reduce the line length of these comments (sorry, just an old formatting thing from the style guidelines).
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 1099 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_MH0zA4aNPmSgiNAG:-Nh_MH0zA4aNPmSgiNAH:bj5cd8n) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L1099)):*
> ```PowerShell
>                 if ($DevDrive)
>                 {
>                     <#
> ```

Should we separate this out into a common function? E.g., a "Compare-PartitionSizeUsingGB" - or something? This is also because the same functionality is used in `Set` as well.
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 36 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_Hh7G3yJWE-en-OTV:-Nh_Hh7KASxlQ1zsYQt-:b-wkhd5u) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L36)):*
> ```PowerShell
> {
>     InModuleScope $script:dscResourceName {
>         $script:testDriveLetter = 'G'
> ```

nit: just for consistency and to make it easier to detect mismatches on the test variables do you want to change `$script:testDriveLetter` to `$script:testDriveLetterG`?
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 1403 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_IM6xECPeqx4Iy97F:-Nh_IM6y3ckpJgRYQSS3:bbkibat) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps [...]

2023-10-25 21:02 UTC, bbonaby reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/278)* status: 7 of 12 files reviewed, 28 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 8 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_NxU8-3DdoVrlOdG6:-NhccrtV9H6U8-XDWDPn:b-oy33ej) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/CHANGELOG.md#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think we should make this a `BREAKING CHANGE:` just because it does change some existing behaviors that "could" break existing configs. This is fine though and will just bump major version to 6.

Also, can you add `### Added` before change line above (with a blank line before it). E.g.

```
### Added

- Disk:
  - BREAKING CHANGE: Added support for volumes to be formatted as Dev Drives - Fixes [Issue #276](https://github.com/dsccommunity/StorageDsc/issues/276)
```

</blockquote></details>

Thanks, updated this
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 36 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_Hh7G3yJWE-en-OTV:-NhccyHR3VjfDIw7H7YR:b-oy33ej) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L36)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: just for consistency and to make it easier to detect mismatches on the test variables do you want to change `$script:testDriveLetter` to `$script:testDriveLetterG`?
</blockquote></details>

Thanks, updated this
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 1403 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_IM6xECPeqx4Iy97F:-NhcczxrBEScCOZP48nA:b-oy33ej) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L1403)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can change this to be `Should -BeTrue` throughout (and also for false can be `Should -BeFalse`)
</blockquote></details>

Thanks, updated this
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 3036 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_IpRC7dQqOJNKD0hW:-Nhcd-fcEw5NPOyHYvQw:b-oy33ej) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L3036)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Dev Drive -> DevDrive (helps indicate a param rather than something else .... although a real nit :D )
</blockquote></details>

Thanks, updated this
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 3088 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_J9DNBi-1GgohjBm3:-Nhcd0BnEIH1rlZBi_Ua:b-oy33ej) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L3088)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Dev Drive -> DevDrive (helps indicate a param rather than something else .... although a real nit :D )
</blockquote></details>

Thanks, updated this
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 3191 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_PNX-6y7r5QI3b1es:-Nhcd0Yb4_JbZegNm1WM:b-oy33ej) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L3191)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Can say `Should throw an exception stating that AllowDestructive flag needs to be set to resize existing partition for DevDrive` :grinning:
</blockquote></details>

Thanks, updated this
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 3222 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_Pjgi4o70jvN_H_um:-Nhcd0ww7b-Qv973qGvj:b-oy33ej) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L3222)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Unlikely to be an issue, but could this be zeroed at the beginning of this Context block in case the code/test is reused?
</blockquote></details>

Thanks, updated this
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 3250 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_Q8eW9SjaiN25xC65:-Nhcd1Pg2Z1IPIyUfz96:b-oy33ej) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L3250)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can include parameter name on the $DriveLetter parameter?
</blockquote></details>

Thanks, updated this
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 3312 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_QG148k67j4LWxpfB:-Nhcd1rLA06BKFfwU-Mp:b-oy33ej) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L3312)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: no need for full stop at end of Context  :grinning:
</blockquote></details>

Thanks, updated this
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 3347 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_QNAu6KVgxFrLW9VH:-Nhcd2JG06cGz10L9lIa:b-af6fav) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L3347)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think we can drop the `MockWith` parameter entirely here?
</blockquote></details>

Thanks, updated this and every where else I used this.
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 3383 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_QvYI105yRZYE8piU:-NhcdCtGDtJ1IPd6FtRu:b-23s7yz) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L3383)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Dev Drive to DevDrive :grinning: and no need for full stop (only mentioned due to Pester output formatting in Azure DevOps .
</blockquote></details>

Thanks, updated this and everywhere else I did this as well.
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 3431 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_QpoTBEJgH4uB46qI:-Nhcd2gOErJgcT1-CmB6:b-23s7yz) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L3431)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: `-f` :grinning:
</blockquote></details>

Thanks, updated this and everywhere else I did this as well.
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 4536 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_RCTa3-4ce0JbDnzY:-NhcdEKC3wAigcbhZgZL:b-xlfnfb) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk.Tests.ps1#L4536)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: -F -> -f  ... and throughout (will ignore any more).
</blockquote></details>

thanks updated
___
*[`tests/Unit/DSC_Disk.Tests.ps1` line 4547 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_RRzD8MXxrBCN6270:-NhcdGv_--L2TR2ugGa4:b-xlfnfb) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/tests/Unit/DSC_Disk [...]

2023-10-25 21:03 UTC, bbonaby commented
Thanks @PlagueHO  I updated the PR and addressed your comments.





<!-- Sent from Reviewable.io -->

2023-10-25 21:06 UTC, bbonaby commented
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 1099 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_MH0zA4aNPmSgiNAG:-Nhcdy6qDHTjk5JbKxIU:bmo1v5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L1099)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should we separate this out into a common function? E.g., a "Compare-PartitionSizeUsingGB" - or something? This is also because the same functionality is used in `Set` as well.
</blockquote></details>

I created a generic function called Compare-SizeUsingGB so we could reuse the same functionality here. Thanks


<!-- Sent from Reviewable.io -->

2023-10-25 21:06 UTC, bbonaby commented
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 402 at r4](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-Nh_Dho86laaswdzJJ5R:-NhcdfP68X7H76K02hgK:b-896fix) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/72391a900f5a9894a9a0e22b4dbb4067e19aa9b3/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L402)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can this be?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-26 17:14 UTC, bbonaby commented
@PlagueHO Thanks for the help with this, if you're all good with these latest changes, would it be possible to get this merged in today or tomorrow?

2023-10-27 06:31 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/278#-:-Nhjp1R14wNwvEnqeUzZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbonaby)



<!-- Sent from Reviewable.io -->

2023-10-27 06:31 UTC, merged