VirtualHardDisk: Resource for creating and attaching a virtual disk
dsccommunity/StorageDsc pull request #279
Opened 2023-09-25 17:53 UTC by bbonaby

#### Pull Request (PR) description

This PR adds a virtual hard disk resource that will allow DSC users to create and attach a virtual hard disk without needing a storage pool or enabling the Hyper-V Windows feature. **Half** of this PR is unit tests. I'll need to add integration tests as this feature should be usable in server 2019 and server 2022 without enabling anything special. But I'd like to start the review process since with the added unit tests the PR is getting big.

#### This Pull Request (PR) fixes the following issues

- Fixes #277

#### Task list

- [x ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x ] Resource documentation added/updated in README.md.
- [x ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ x] Comment-based help added/updated.
- [x ] Localization strings added/updated in all localization files as appropriate.
- [ x] Examples appropriately added/updated.
- [ x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2023-09-26 02:45 UTC, bbonaby commented
FYI @PlagueHO, thanks! I'll work on an integration test for this in the mean time

2023-09-27 06:30 UTC, PlagueHO commented
Thanks @bbonaby - I've blocked out sometime to get the review done either tomorrow arvo or on the weekend.

2023-10-25 06:35 UTC, PlagueHO requested changes
Have run out of time tonight @bbonaby to finish review, but will try and get some more time on this tomorrow night.

> Reviewed 1 of 13 files at r1, 4 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-:-Nh_XjmuCZns6DHcCGeQ:bi7e033)* status: 5 of 13 files reviewed, 14 unresolved discussions (waiting on @bbonaby)

___
*[`CHANGELOG.md` line 8 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_TR8-BqeKBncjtl15:-Nh_TR802w6Mt9nzUfyH:brlw9a1) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/CHANGELOG.md#L8)):*
> ```Markdown
> ## [Unreleased]
> 
> - Added DSC_VirtualHardDisk resource for creating virtual disks and tests. - Fixes [Issue #277](https://github.com/dsccommunity/StorageDsc/issues/277)
> ```

Can we add this to an `### Added` section above and also remove the fullstop at the end of the description. E.g.

```
### Added

- Added DSC_VirtualHardDisk resource for creating virtual disks and tests - Fixes [Issue #277](https://github.com/dsccommunity/StorageDsc/issues/277)
````
___
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 283 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_TkGO2De8o2Q7v3n-:-Nh_TkGO2De8o2Q7v3n0:b6w8ibp) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L283)):*
> ```PowerShell
>     }
> 
>     if ($disk.PartitionStyle -eq 'RAW' -bor (-not $disk.PartitionStyle))
> ```

I noticed this was removed in the previous PR (DevDrive) - is this intentional?
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof` line 5 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_WBPHCPEQZx09baZn:-Nh_WBPHCPEQZx09baZo:b-l8cude) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof#L5)):*
> ```
> class DSC_VirtualHardDisk : OMI_BaseResource
> {
>     [Key, Description("Specifies the full path to the virtual hard disk file that will be created or attached. This must include the extension, and the extension must match the disk format.")] String FilePath;
> ```

"created _or_ attached" - should this be "created and attached" ? E.g., is there a way this resource can create the vhd/x without attaching it?
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof` line 6 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_WPRzBQ9S34VhYCtW:-Nh_WPS-04Xbnj4demfe:b4lq6a4) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof#L6)):*
> ```
> {
>     [Key, Description("Specifies the full path to the virtual hard disk file that will be created or attached. This must include the extension, and the extension must match the disk format.")] String FilePath;
>     [Write, Description("Specifies the size the of virtual hard disk.")] Uint64 DiskSize;
> ```

nit: Specifies the size the of virtual hard disk -> Specifies the size of virtual hard disk to create if it doesn't exist and Ensure is present.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof` line 7 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_X9UlCKrrOnJ2Kb7s:-Nh_X9UlCKrrOnJ2Kb7t:b-jdm6pv) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof#L7)):*
> ```
>     [Key, Description("Specifies the full path to the virtual hard disk file that will be created or attached. This must include the extension, and the extension must match the disk format.")] String FilePath;
>     [Write, Description("Specifies the size the of virtual hard disk.")] Uint64 DiskSize;
>     [Write, Description("Specifies the disk type the virtual hard disk should use."), ValueMap{"Fixed","Dynamic"}, Values{"Fixed","Dynamic"}] String DiskType;
> ```

nit: Specifies the disk type the virtual hard disk should use. -> Specifies the disk type of virtual hard disk to create if it doesn't exist and Ensure is present.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof` line 8 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_XNvQAIko4N68lh-Q:-Nh_XNvU-jeX2jPI9yZ-:b-ozi2w7) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof#L8)):*
> ```
>     [Write, Description("Specifies the size the of virtual hard disk.")] Uint64 DiskSize;
>     [Write, Description("Specifies the disk type the virtual hard disk should use."), ValueMap{"Fixed","Dynamic"}, Values{"Fixed","Dynamic"}] String DiskType;
>     [Write, Description("Specifies the disk format the virtual hard disk should use. Defaults to Vhdx."), ValueMap{"Vhd","Vhdx"}, Values{"Vhd","Vhdx"}] String DiskFormat;
> ```

nit: Specifies the disk format the virtual hard disk should use. Defaults to Vhdx. -> Specifies the disk format the virtual hard disk should use or create if it does not exist and Ensure is present. Defaults to Vhdx.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof` line 9 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_Xa0q70vF4du90_ja:-Nh_Xa0rCiNKU1X-bVa1:bpmpwfe) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof#L9)):*
> ```
>     [Write, Description("Specifies the disk type the virtual hard disk should use."), ValueMap{"Fixed","Dynamic"}, Values{"Fixed","Dynamic"}] String DiskType;
>     [Write, Description("Specifies the disk format the virtual hard disk should use. Defaults to Vhdx."), ValueMap{"Vhd","Vhdx"}, Values{"Vhd","Vhdx"}] String DiskFormat;
>     [Write, Description("Determines whether the virtual hard disk should be created and attached or should not be attached."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
> ```

nit: should not be attached -> should be detatched if it exists.
___
*[`source/DSCResources/DSC_VirtualHardDisk/README.md` line 7 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_UZRFE4BQCd8R8JzO:-Nh_UZRFE4BQCd8R8JzP:b-slgsdh) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/README.md#L7)):*
> ```Markdown
> There are 2 high level scenarios, one where the user uses the 'Present' flag and the second when the user uses the 'Absent' flag in the resource.
> 
> 1. When the 'Present' flag is used the resource checks if the virtual hard disk is on the machine using the file path that is entered.
> ```

For md, use 1. for each item (regardless of the actual number or letter). This is because md renderers will auto number items. I think our automatic md testing will highlight this as well (but isn't because of the blank lines between entries :grinning:)

Can also remove blank lines between items.
___
*[`source/DSCResources/DSC_VirtualHardDisk/README.md` line 9 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_Wr7Q0XXloZIuR1ZX:-Nh_Wr7RESxUDH7CILDS:br8ihp) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/README.md#L9)):*
> ```Markdown
> 1. When the 'Present' flag is used the resource checks if the virtual hard disk is on the machine using the file path that is entered.
> 
>     a. If the file path is correct and it is confirmed to be the location of a real virtual hard disk file. The resource will do nothing.
> ```

Will the resource attach the virtual hard disk if it is not attache [...]

2023-10-27 06:32 UTC, PlagueHO commented
Hi @bbonaby - now that the other PR is merged, can you resolve the conflicts and I'll finish reviewing this one.

2023-10-27 19:57 UTC, bbonaby commented
*[`source/DSCResources/DSC_Disk/DSC_Disk.psm1` line 283 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_TkGO2De8o2Q7v3n-:-NhmcLWI0JVYMKLQrmEd:b2fbntx) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_Disk/DSC_Disk.psm1#L283)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I noticed this was removed in the previous PR (DevDrive) - is this intentional?
</blockquote></details>

oh actually this can be removed. I had initially thought that $disk.PartitionStyle could be null when a disk is initially created/inserted into the system that does not have a partition style. But even in those cases 'RAW' is still returned. So I removed it from there, I believe it ended up here from when I was testing the new DevDrive flag in the Disk resource with this resource. I'll remove this addition thanks.


<!-- Sent from Reviewable.io -->

2023-10-27 20:08 UTC, bbonaby commented
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof` line 5 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_WBPHCPEQZx09baZn:-Nhmk3Fl0PKqzzDTiYsD:b-xlfnfb) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof#L5)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

"created _or_ attached" - should this be "created and attached" ? E.g., is there a way this resource can create the vhd/x without attaching it?
</blockquote></details>

thanks updated


<!-- Sent from Reviewable.io -->

2023-10-27 20:17 UTC, bbonaby commented
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof` line 9 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_Xa0q70vF4du90_ja:-Nhmm5HV7B5ai3zM_00C:b-xlfnfb) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: should not be attached -> should be detatched if it exists.
</blockquote></details>

thanks updated


<!-- Sent from Reviewable.io -->

2023-10-27 20:19 UTC, bbonaby commented
Updating this today to resolve the merge conflicts and address the initial comments. Looks like I prematurely replied to your previous comment so sorry about that. I'll keep them as drafts before I push the update commit. Thanks

2023-10-28 04:15 UTC, bbonaby commented
*[`source/DSCResources/DSC_VirtualHardDisk/README.md` line 9 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_Wr7Q0XXloZIuR1ZX:-NhoUZK_5XVsV_lqawGf:b-jxphqv) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/README.md#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Will the resource attach the virtual hard disk if it is not attached?
</blockquote></details>

updated and clarified the behavior a bit more thanks.


<!-- Sent from Reviewable.io -->

2023-10-28 04:16 UTC, bbonaby commented
*[`source/DSCResources/DSC_VirtualHardDisk/README.md` line 11 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_WVXG9S5cyhsIdSbP:-NhoUeQiCh0RUtcZOSOH:bxzjjx0) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/README.md#L11)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

If the real vhd/vhdx exists but is not attached, but the size and/or disktype is different, what happens?
</blockquote></details>

updated and clarified how disksize and disktype are used. Thanks


<!-- Sent from Reviewable.io -->

2023-10-28 04:17 UTC, bbonaby commented
*[`source/DSCResources/DSC_VirtualHardDisk/README.md` line 28 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_VHpH8_RkQboxsCzQ:-NhoUoOt-4RwE_7QZiot:b-febffi) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/README.md#L28)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we add a warning here that using both DSC_VirtualHardDisk and DSC_VHD in the same config/machine could result in an invalid config (not that anyone would... but we never know :grinning: )
</blockquote></details>

updated and added a note about how they shouldn't be used together. I started the sentence off with 'Note:' . Let me know if you rather me put 'Warning:' thanks.


<!-- Sent from Reviewable.io -->

2023-10-28 04:17 UTC, bbonaby commented
*[`source/DSCResources/DSC_VirtualHardDisk/README.md` line 33 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_VuFL-VFWonVod1E8:-NhoV1UWCr0F59L37I8P:bjcogm5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/README.md#L33)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

See comments about markdown autonumbering above. Can also use the VS Markdown linting extension to automatically get this suggestion.
</blockquote></details>

updated, thanks for the tip 😊 hope it looks better now. Let me know if you see any more issues. Thanks


<!-- Sent from Reviewable.io -->

2023-10-28 04:18 UTC, bbonaby commented
*[`source/Modules/VirtualHardDisk.Win32Helpers/VirtualHardDisk.Win32Helpers.psm1` line  at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_UC5Q8SJmxE9yFVay:-NhoVAYn5ZLDw5M-ecvF:b-fdapof) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/Modules/VirtualHardDisk.Win32Helpers/VirtualHardDisk.Win32Helpers.psm1#L)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

To help associate any imported modules with the DSC resource, can we name this as `StorageDsc.VirtualHardDisk.Win32Helpers` - or something to that effect?
</blockquote></details>

updated and changed the name to `StorageDsc.VirtualHardDisk.Win32Helpers` thanks


<!-- Sent from Reviewable.io -->

2023-10-28 04:19 UTC, bbonaby reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/279)* status: 0 of 15 files reviewed, 14 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 8 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_TR8-BqeKBncjtl15:-NhmcC0y57rv4cp1SJxc:b1wjbw5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/CHANGELOG.md#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we add this to an `### Added` section above and also remove the fullstop at the end of the description. E.g.

```
### Added

- Added DSC_VirtualHardDisk resource for creating virtual disks and tests - Fixes [Issue #277](https://github.com/dsccommunity/StorageDsc/issues/277)
````
</blockquote></details>

Thanks, updated.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof` line 6 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_WPRzBQ9S34VhYCtW:-Nhmm3r75R-M8td0Zb6x:b-xlfnfb) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof#L6)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Specifies the size the of virtual hard disk -> Specifies the size of virtual hard disk to create if it doesn't exist and Ensure is present.
</blockquote></details>

thanks updated
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof` line 7 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_X9UlCKrrOnJ2Kb7s:-Nhmm4IECj8d1VOUTAIV:b-xlfnfb) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Specifies the disk type the virtual hard disk should use. -> Specifies the disk type of virtual hard disk to create if it doesn't exist and Ensure is present.
</blockquote></details>

thanks updated
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof` line 8 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_XNvQAIko4N68lh-Q:-Nhmm4rT4ZK0hAOWvZgT:b-xlfnfb) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.schema.mof#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Specifies the disk format the virtual hard disk should use. Defaults to Vhdx. -> Specifies the disk format the virtual hard disk should use or create if it does not exist and Ensure is present. Defaults to Vhdx.
</blockquote></details>

thanks updated
___
*[`source/DSCResources/DSC_VirtualHardDisk/README.md` line 7 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_UZRFE4BQCd8R8JzO:-Nhmph-u0jd2FSn9pK09:bpy5aoj) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/README.md#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

For md, use 1. for each item (regardless of the actual number or letter). This is because md renderers will auto number items. I think our automatic md testing will highlight this as well (but isn't because of the blank lines between entries :grinning:)

Can also remove blank lines between items.
</blockquote></details>

updated, thanks


<!-- Sent from Reviewable.io -->

2023-10-28 04:19 UTC, bbonaby commented
*[`source/DSCResources/DSC_VirtualHardDisk/README.md` line 32 at r3](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nh_VjWN0YAmI_z-Lvi0:-NhoVb6e2ZkYObx2IotM:b-53rppp) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/937e81fd6a17144227787fa515334d1f2b0af3d1/source/DSCResources/DSC_VirtualHardDisk/README.md#L32)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: wrap .vhd and .vhdx in backtick to highlight as code (even though not really code :D)
</blockquote></details>

updated thanks


<!-- Sent from Reviewable.io -->

2023-10-28 17:34 UTC, johlju commented
@bbonaby please rebase this on (pull in changes from main) and hopefully @PlagueHO will come around soon and finish the review. 🙂

2023-10-30 19:33 UTC, PlagueHO commented
@bbonaby - can you resolve the conflicts on this one (caused #283).

2023-10-31 02:23 UTC, bbonaby commented
Thanks @PlagueHO  conflicts should be all resolved now

2023-11-09 22:14 UTC, bbonaby commented
Hey @PlagueHO any update on this?

2023-11-17 21:26 UTC, PlagueHO reviewed
Apologies @bbonaby - been so snowed under the last couple of weeks this slipped off my radar. Will do this tonight. 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-:-NjUAIwG05SIrwl1zE6x:b-i3moaj)* status: 0 of 15 files reviewed, 14 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-02-13 22:58 UTC, bbonaby commented
hey @PlagueHO  any update on this PR?

2024-02-21 05:31 UTC, PlagueHO commented
Hi @bbonaby - apologies, DSC has just managed to slip off my radar due to day job commitments. But I'll bump this one up and aim for it on the weekend. Again, apologies.

2024-03-01 05:08 UTC, PlagueHO reviewed
> Reviewed 3 of 11 files at r3, 3 of 10 files at r5, 1 of 1 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/279)* status: 8 of 15 files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-03-02 00:19 UTC, PlagueHO requested changes
Hi @bbonaby - sorry about the delay. I've finished reviewing all the files now - nothing major just some style bits and pieces.

One question: how easy/would it be possible to add integration tests for this resource?

> Reviewed 1 of 11 files at r3, 7 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-:-NrwWaSZ2RFTwOnXoYZi:bzewo2c)* status: all files reviewed, 43 unresolved discussions (waiting on @bbonaby)

___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 33 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-NrwBcMp5z5Pme2QHY1l:-NrwBcMp5z5Pme2QHY1m:b-qoq7ln) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L33)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
>         [String]
> ```

nit: avoid type accelerators.



_Suggestion:_
```PowerShell
[System.String]
```
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 43 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw1zAuCHOGcZCR_Z82:-Nrw1zAuCHOGcZCR_Z83:b30vzfj) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L43)):*
> ```PowerShell
> 
>     $diskImage = Get-DiskImage -ImagePath $FilePath -ErrorAction SilentlyContinue
>     $Ensure = 'Present'
> ```

nit: lower case for local vars.



_Suggestion:_
```PowerShell
$ensure = 'Present'
```
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 47 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw1wLJ0dUpezE01fep:-Nrw1_ky-9dHhZoqvImQ:b30vzfj) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L47)):*
> ```PowerShell
>     if (-not $diskImage)
>     {
>         $Ensure = 'Absent'
> ```

nit: lower case for local vars.



_Suggestion:_
```PowerShell
$ensure = 'Absent'
```
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 56 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw1kurBoELGmNxxaLh:-Nrw1kurBoELGmNxxaLi:b30vzfj) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L56)):*
> ```PowerShell
>         Size       = $diskImage.Size
>         DiskNumber = $diskImage.DiskNumber
>         Ensure     = $Ensure
> ```

nit: lower case for local vars.



_Suggestion:_
```PowerShell
Ensure     = $ensure
```
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 86 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-NrwBiW23w4eEXNgif9P:-NrwBiW33qcV4O0Ac1Om:b-qoq7ln) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L86)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
>         [String]
> ```

nit: avoid type accelerators.



_Suggestion:_
```PowerShell
[System.String]
```
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 112 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw6DWW8-TRUEhggFrr:-Nrw6DWX-ZQTjVSD2zhY:b-nk93dr) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L112)):*
> ```PowerShell
>     Assert-ParametersValid -FilePath $FilePath -DiskSize $DiskSize -DiskFormat $DiskFormat
> 
>     $resource = Get-TargetResource -FilePath $FilePath
> ```

nit: Maybe rename variable to `$currentState` to indicate that this is the current state of the virtual disk? Also aligns to style in other resources.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 144 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw6ved2GxZ079dop0U:-Nrw6ved2GxZ079dop0V:b-2j8o2l) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L144)):*
> ```PowerShell
>                 {
>                     Write-Verbose -Message ($script:localizedData.RemovingCreatedVirtualHardDiskFile -f $FilePath)
>                     Remove-Item $FilePath -verbose
> ```

Should we attempt with `-Force` and `-Confirm:No`?

Also capital V in verbose. 



_Suggestion:_
```PowerShell
Remove-Item $FilePath -Verbose
```
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 149 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw6_uICVhg2EuaVF8z:-Nrw6_uICVhg2EuaVF9-:b-2j8o2l) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L149)):*
> ```PowerShell
>                 if ($wasLocationCreated)
>                 {
>                     Remove-Item -LiteralPath $folderPath -verbose
> ```

Should we attempt with `-Force` and `-Confirm:No`?

Also capital V in verbose. 



_Suggestion:_
```PowerShell
Remove-Item -LiteralPath $folderPath -Verbose
```
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 170 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-NrwBRYrAUI398IUgxdb:-NrwBRYrAUI398IUgxdc:b47dkol) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L170)):*
> ```PowerShell
>     else
>     {
>         # Detach the virtual hard disk if its not suppose to be attached.
> ```

nit: comment correction.



_Suggestion:_
```PowerShell
# Detach the virtual hard disk if its not supposed to be attached.
```
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 211 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-NrwBmvt-euPQ6g_ZSQ0:-NrwBmvt-euPQ6g_ZSQ1:b-qoq7ln) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L211)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
>         [String]
> ```

nit: avoid type accelerators.



_Suggestion:_
```PowerShell
[System.String]
```
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 237 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-NrwC1lG27VeAxYDSt92:-NrwC-XdDhIlFwUyzD5Z:b-nk93dr) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L237)):*
> ```PowerShell
>     Assert-ParametersValid -FilePath $FilePath -DiskSize $DiskSize -DiskFormat $DiskFormat
> 
>     $resource = Get-TargetResource -FilePath $FilePath
> ```

nit: Maybe rename variable to `$currentState` to indicate that this is the current state of the virtual disk? Also aligns to style in other resources.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 306 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw2ZHeBqIydZK_O_Gz:-Nrw2ZHeBqIydZK_O_H-:bmbo3tt) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L306)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
>         [String]
> ```

nit: avoid using type accelerators.



_Suggestion:_
```PowerShell
[System.String]
```
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk. [...]

2024-03-08 18:39 UTC, bbonaby commented
Thanks @PlagueHO What I'll do it update the PR with your requested changes first, then when you're all good with them. Add the Integration test. Is that all good with you?

2024-03-10 23:17 UTC, PlagueHO commented
Ok @bbonaby - that is all good - wasn't sure we could add them, but if it's possible we can add them later.

2024-08-07 17:56 UTC, johlju commented
For the build to pass the line: https://github.com/dsccommunity/StorageDsc/blob/06a30de47e7adf41e86efc1b9ca9d2a7c1540dee/azure-pipelines.yml#L30

Need to be change to:

```bash
dotnet tool install --global GitVersion.Tool --version 5.*
```

This is due to GitVersion 6 that was release has breaking changes that are not yet support by the Sampler pipeline.

2024-08-20 19:22 UTC, bbonaby reviewed
Thanks, I updated the PR. To add this line.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-:-O4lDlTwBVK1hSrppRH8:b3qz46z)* status: 6 of 19 files reviewed, 44 unresolved discussions (waiting on @PlagueHO)

___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 43 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw1zAuCHOGcZCR_Z82:-O4kufObB4GkyHqb4d17:b1wjbw5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L43)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: lower case for local vars.
</blockquote></details>

Thanks, updated.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 47 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw1wLJ0dUpezE01fep:-O4kujFtAtFmzOIahcZY:b-munwrr) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L47)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: lower case for local vars.
</blockquote></details>

Thanks, updated
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 56 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw1kurBoELGmNxxaLh:-O4kukdl2GlQx_6oEqcU:b1wjbw5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L56)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: lower case for local vars.
</blockquote></details>

Thanks, updated.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 86 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-NrwBiW23w4eEXNgif9P:-O4kumQQ9vJhuDVIhoTe:b-c0gtaj) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L86)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: avoid type accelerators.
</blockquote></details>

Thanks, updated.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 112 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw6DWW8-TRUEhggFrr:-O4kunFh4x07e9UdWxth:b1wjbw5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L112)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Maybe rename variable to `$currentState` to indicate that this is the current state of the virtual disk? Also aligns to style in other resources.
</blockquote></details>

Thanks, updated.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 144 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw6ved2GxZ079dop0U:-O4kuyhW4ejU2n49VP16:b1wjbw5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L144)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should we attempt with `-Force` and `-Confirm:No`?

Also capital V in verbose.
</blockquote></details>

Thanks, updated.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 149 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw6_uICVhg2EuaVF8z:-O4kuzx58Aog1qt3XDLO:b1wjbw5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L149)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should we attempt with `-Force` and `-Confirm:No`?

Also capital V in verbose.
</blockquote></details>

Thanks, updated.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 211 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-NrwBmvt-euPQ6g_ZSQ0:-O4kv7EM2L083vLutDKK:b1wjbw5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L211)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: avoid type accelerators.
</blockquote></details>

Thanks, updated.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 237 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-NrwC1lG27VeAxYDSt92:-O4kv8CW6gHnx2t0jtu1:b1wjbw5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L237)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Maybe rename variable to `$currentState` to indicate that this is the current state of the virtual disk? Also aligns to style in other resources.
</blockquote></details>

Thanks, updated.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 306 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw2ZHeBqIydZK_O_Gz:-O4kv9Q87b7ens4U08Dk:b1wjbw5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L306)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: avoid using type accelerators.
</blockquote></details>

Thanks, updated.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 311 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw2vPH4wN-p_Cn9bZx:-O4kvBHQDn3RszI5gFEI:bynh6e) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L311)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should there also be a validate `$DiskSize` is greater than zero? `[ValidateScript({$ -gt 0})]`- although I can see that this would be detected lower down anyway.
</blockquote></details>

Thanks, I added a validationScript tag
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 359 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw5Eri-02Pvx6O7v77:-O4kvFbU3ECIWCs6D7C_:b-munwrr) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L359)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: lower case
</blockquote></details>

Thanks, updated
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 363 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw5J1U1DboEvfZmOYU:-O4kvGoHDemfeH5M-omw:b1wjbw5) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L363)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: style tweaks.
</blockquote></details>

Thanks, updated.
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 367 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-Nrw5Q7h6mZkwSEkcaRP:-O4kvIBZ2tPFyDVkXkUT:b1wjb [...]

2024-08-20 19:24 UTC, bbonaby commented
@PlagueHO Sorry it took so long getting back to you, was busy with MS Build 2024 at the time, then summer hit. I updated the PR   based on your comments and also added integration tests as well, thanks for your patience.

2024-08-23 05:44 UTC, PlagueHO commented
No problem @bbonaby - will review this weekend (day job stuff got in the way this week).

2024-09-09 05:18 UTC, PlagueHO requested changes
THanks for your patience @bbonaby - Just some super minor bits. Ping my on Teams when good to go.

> Reviewed 1 of 1 files at r9, 11 of 12 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-:-O6KCkWc0I5IJP_5JUBY:b9n4rkm)* status: all files reviewed, 12 unresolved discussions (waiting on @bbonaby)

___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 112 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6K8ziM7G3MWodgBK-9:-O6K8ziNESxqqnoYApt4:b-5filtq) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L112)):*
> ```PowerShell
>     Assert-ParametersValid -FilePath $FilePath -DiskSize $DiskSize -DiskFormat $DiskFormat
> 
>     if (-not (Test-RunningAsAdministrator))
> ```

Is it possible to use `Assert-ElevatedUser` in `DSCResource.Common` for this? I haven't checked in detail, but it looks like it's the same implementation?
___
*[`source/DSCResources/DSC_VirtualHardDisk/en-US/DSC_VirtualHardDisk.strings.psd1` line 17 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6K79DL3YUCjxvrXwFB:-O6K79DL3YUCjxvrXwFC:b-mxjmd3) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/source/DSCResources/DSC_VirtualHardDisk/en-US/DSC_VirtualHardDisk.strings.psd1#L17)):*
> ```PowerShell
>     GettingVirtualHardDisk = Getting virtual hard disk information for virtual hard disk located at '{0}.
>     RemovingCreatedVirtualHardDiskFile = The virtual hard disk file at location '{0}' is being removed due to an error while attempting to mount it to the system.
>     VirtualDiskAdminError = Creating and mounting a virtual disk requires running PowerShell as an Administrator. Please launch PowerShell as Administrator and try again.
> ```

nit: Thinking about the wording of this message: If the resource is applied by the LCM them it won't be performed by launching PS. I guess though, the LCM usually runs as Administrator anyway, so this issue shouldn't occur. But maybe state: "Creating and mounting a virtual disk requires running local Administrator permissions. Please ensure this resource is being applied with an account with local Administrator permissions." - or something like that?
___
*[`source/Modules/StorageDsc.Common/StorageDsc.Common.psm1` line 645 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O4l91LJ9znjmTy_TjZz:-O6K9SdS34yiLIDJF_12:b-5filtq) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/source/Modules/StorageDsc.Common/StorageDsc.Common.psm1#L645)):*
<details><summary><i>Previously, bbonaby (Branden Bonaby) wrote…</i></summary><blockquote>

@PlagueHO I added this new method because running the Set-DscResource isn't guaranteed to be running in a process with admin privileges. Mounting a disk requires running elevated.
</blockquote></details>

Is it possible to use `Assert-ElevatedUser` in `DSCResource.Common` for this? I haven't checked in detail, but it looks like it's the same implementation?
___
*[`tests/Integration/DSC_VirtualHardDisk.config.ps1` line 1 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6KAzNP8prPFhm7R-cv:-O6KAzNP8prPFhm7R-cw:b-whvat9) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/tests/Integration/DSC_VirtualHardDisk.config.ps1#L1)):*
> ```PowerShell
> $TestFixedVirtualHardDiskVhd = @{
> ```

Can we move this block into a $configData block in the *.Integration.Tests.ps1 file? E.g., like this: [ComputerManagementDsc/tests/Integration/DSC\_SystemLocale.Integration.Tests.ps1 at main · dsccommunity/ComputerManagementDsc (github.com)](https://github.com/dsccommunity/ComputerManagementDsc/blob/main/tests/Integration/DSC_SystemLocale.Integration.Tests.ps1#L36)
___
*[`tests/Integration/DSC_VirtualHardDisk.config.ps1` line 8 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6KB9yL4SWsWNbQDMzq:-O6KB9yL4SWsWNbQDMzr:b-whvat9) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/tests/Integration/DSC_VirtualHardDisk.config.ps1#L8)):*
> ```PowerShell
> }
> 
> $TestDynamicVirtualHardDiskVhdx = @{
> ```

Can we move this block into a $configData block in the *.Integration.Tests.ps1 file? E.g., like this: [ComputerManagementDsc/tests/Integration/DSC\_SystemLocale.Integration.Tests.ps1 at main · dsccommunity/ComputerManagementDsc (github.com)](https://github.com/dsccommunity/ComputerManagementDsc/blob/main/tests/Integration/DSC_SystemLocale.Integration.Tests.ps1#L36)
___
*[`tests/Integration/DSC_VirtualHardDisk.Integration.Tests.ps1` line 27 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6KBD8b7xnxrDMeZR65:-O6KBD8b7xnxrDMeZR66:b-1ubppv) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/tests/Integration/DSC_VirtualHardDisk.Integration.Tests.ps1#L27)):*
> ```PowerShell
> 
>     Describe "$($script:dscResourceName)_CreateAndAttachFixedVhd_Integration" {
>         Context 'Create and attach a fixed virtual disk' {
> ```

Could you copy the integration test pattern from ComputerManagementDsc: [ComputerManagementDsc/tests/Integration/DSC\_SystemLocale.Integration.Tests.ps1 at main · dsccommunity/ComputerManagementDsc (github.com)](https://github.com/dsccommunity/ComputerManagementDsc/blob/main/tests/Integration/DSC_SystemLocale.Integration.Tests.ps1#L35)

Specifically, spit the "compile and apply" into two It blocks and use the $configData object.
___
*[`tests/Integration/DSC_VirtualHardDisk.Integration.Tests.ps1` line 43 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6KBXmS2Bi0bOnC9Oea:-O6KBXmS2Bi0bOnC9Oeb:b-3v0g11) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/tests/Integration/DSC_VirtualHardDisk.Integration.Tests.ps1#L43)):*
> ```PowerShell
>                     $_.ConfigurationName -eq "$($script:dscResourceName)_CreateAndAttachFixedVhd_Config"
>                 }
>                 $currentState.FilePath   | Should -Be $script:TestFixedVirtualHardDiskVhd.FilePath
> ```

Once the $configData object is implemented, these tests can compare the values against the properties in that object. E.g. [ComputerManagementDsc/tests/Integration/DSC\_UserAccountControl.Integration.Tests.ps1 at main · dsccommunity/ComputerManagementDsc (github.com)](https://github.com/dsccommunity/ComputerManagementDsc/blob/main/tests/Integration/DSC_UserAccountControl.Integration.Tests.ps1#L102)
___
*[`tests/Unit/DSC_VirtualHardDisk.Tests.ps1` line 168 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-NrwTofoAABrhmWDzjSI:-O6KCCnD9nFqfrnbU2_E:b-5x4hmu) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/tests/Unit/DSC_VirtualHardDisk.Tests.ps1#L168)):*
<details><summary><i>Previously, bbonaby (Branden Bonaby) wrote…</i></summary><blockquote>

I'm not sure what you mean here. Could you explain it a bit more?
</blockquote></details>

I mean, should the context be "When file path does exist and is currently mounted"' 
___
*[`tests/Unit/DSC_VirtualHardDisk.Tests.ps1` line 137 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6KC-qYE4dP8WJSKo0E:-O6KC-qYE4dP8WJSKo0F:bvnqrb7) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/tests/Unit/DSC_VirtualHardDisk.Tests.ps1#L137)):*
> ```PowerShell
>         }
> 
>         function Test-RunningAsAdministrator
> ```

Might not need this if use the Assert from DSCResource.Common.
___
*[`source/Modules/StorageDsc.VirtualHardDisk.Win32Helpers/StorageDsc.VirtualHardDisk.Win32Helpers.psm1` line 156 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6K9g6bB6LJIDO8_l [...]

2024-09-13 00:59 UTC, bbonaby reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/279)* status: 12 of 19 files reviewed, 12 unresolved discussions (waiting on @PlagueHO)

___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 170 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-NrwBRYrAUI398IUgxdb:-O6cs4Dm2yHi60LhvHXR:bpy5aoj) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L170)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: comment correction.
</blockquote></details>

updated, thanks
___
*[`source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1` line 112 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6K8ziM7G3MWodgBK-9:-O6cs5yU7WNHl1RmR8do:b-5zvmm) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/source/DSCResources/DSC_VirtualHardDisk/DSC_VirtualHardDisk.psm1#L112)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is it possible to use `Assert-ElevatedUser` in `DSCResource.Common` for this? I haven't checked in detail, but it looks like it's the same implementation?
</blockquote></details>

yea that works, I updated this. Thanks
___
*[`source/DSCResources/DSC_VirtualHardDisk/en-US/DSC_VirtualHardDisk.strings.psd1` line 17 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6K79DL3YUCjxvrXwFB:-O6cs0uN8kSn-mmWIDoL:bx36h1j) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/source/DSCResources/DSC_VirtualHardDisk/en-US/DSC_VirtualHardDisk.strings.psd1#L17)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Thinking about the wording of this message: If the resource is applied by the LCM them it won't be performed by launching PS. I guess though, the LCM usually runs as Administrator anyway, so this issue shouldn't occur. But maybe state: "Creating and mounting a virtual disk requires running local Administrator permissions. Please ensure this resource is being applied with an account with local Administrator permissions." - or something like that?
</blockquote></details>

Oh that sounds good. I updated the text. Thanks
___
*[`source/Modules/StorageDsc.Common/StorageDsc.Common.psm1` line 645 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O4l91LJ9znjmTy_TjZz:-O6cqtb6CfzixR64g9F0:b-i2vwlu) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/source/Modules/StorageDsc.Common/StorageDsc.Common.psm1#L645)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is it possible to use `Assert-ElevatedUser` in `DSCResource.Common` for this? I haven't checked in detail, but it looks like it's the same implementation?
</blockquote></details>

yea, you're right. I updated this. Thanks. Now that I know this I can make a PR to fix this Dev Drive issue about not telling the user they need to run as administrator: [Dev Drive DSC error message when not run as admin · Issue #284 · dsccommunity/StorageDsc (github.com)](https://github.com/dsccommunity/StorageDsc/issues/284)
___
*[`tests/Integration/DSC_VirtualHardDisk.config.ps1` line 1 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6KAzNP8prPFhm7R-cv:-O6crK8ICGLmfKU3Tqzg:b-agutbg) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/tests/Integration/DSC_VirtualHardDisk.config.ps1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we move this block into a $configData block in the *.Integration.Tests.ps1 file? E.g., like this: [ComputerManagementDsc/tests/Integration/DSC\_SystemLocale.Integration.Tests.ps1 at main · dsccommunity/ComputerManagementDsc (github.com)](https://github.com/dsccommunity/ComputerManagementDsc/blob/main/tests/Integration/DSC_SystemLocale.Integration.Tests.ps1#L36)
</blockquote></details>

thanks, updated. The only thing I kept was the file path, since it's needed in the "AfterAll" case when the integration test is cleaning up the virtual disk. At that point the $configData doesn't exist anymore.
___
*[`tests/Integration/DSC_VirtualHardDisk.config.ps1` line 8 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6KB9yL4SWsWNbQDMzq:-O6crj0uBbETwwAdSkt7:b-agutbg) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/tests/Integration/DSC_VirtualHardDisk.config.ps1#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can we move this block into a $configData block in the *.Integration.Tests.ps1 file? E.g., like this: [ComputerManagementDsc/tests/Integration/DSC\_SystemLocale.Integration.Tests.ps1 at main · dsccommunity/ComputerManagementDsc (github.com)](https://github.com/dsccommunity/ComputerManagementDsc/blob/main/tests/Integration/DSC_SystemLocale.Integration.Tests.ps1#L36)
</blockquote></details>

thanks, updated. The only thing I kept was the file path, since it's needed in the "AfterAll" case when the integration test is cleaning up the virtual disk. At that point the $configData doesn't exist anymore.
___
*[`tests/Integration/DSC_VirtualHardDisk.Integration.Tests.ps1` line 27 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6KBD8b7xnxrDMeZR65:-O6crjuq0ueHdAhYHLYz:b-xlfnfb) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/tests/Integration/DSC_VirtualHardDisk.Integration.Tests.ps1#L27)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you copy the integration test pattern from ComputerManagementDsc: [ComputerManagementDsc/tests/Integration/DSC\_SystemLocale.Integration.Tests.ps1 at main · dsccommunity/ComputerManagementDsc (github.com)](https://github.com/dsccommunity/ComputerManagementDsc/blob/main/tests/Integration/DSC_SystemLocale.Integration.Tests.ps1#L35)

Specifically, spit the "compile and apply" into two It blocks and use the $configData object.
</blockquote></details>

thanks updated
___
*[`tests/Integration/DSC_VirtualHardDisk.Integration.Tests.ps1` line 43 at r11](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-O6KBXmS2Bi0bOnC9Oea:-O6crlCc67Di2zasAH6o:b-xlfnfb) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/3ebf094fc8a9422f19cf13376fd6562074ebfb1f/tests/Integration/DSC_VirtualHardDisk.Integration.Tests.ps1#L43)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Once the $configData object is implemented, these tests can compare the values against the properties in that object. E.g. [ComputerManagementDsc/tests/Integration/DSC\_UserAccountControl.Integration.Tests.ps1 at main · dsccommunity/ComputerManagementDsc (github.com)](https://github.com/dsccommunity/ComputerManagementDsc/blob/main/tests/Integration/DSC_UserAccountControl.Integration.Tests.ps1#L102)
</blockquote></details>

thanks updated
___
*[`tests/Unit/DSC_VirtualHardDisk.Tests.ps1` line 168 at r8](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-NrwTofoAABrhmWDzjSI:-O6crwp50lMlaACltatN:b-j7hyyg) ([raw file](https://github.com/dsccommunity/StorageDsc/blob/48d66898448aab2f2d3793e46dae4fa0adee07fb/tests/Unit/DSC_VirtualHardDisk.Tests.ps1#L168)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I mean, should the context be "When file path does exist and is currently mounted"'
</blockquote></details>

Oh I see. Updated the text. Thanks
___
*[`tests/Unit/DSC_VirtualHardDisk.Tests.ps1` line 137 at r11](https://reviewable.io/reviews/dsccommunity/ [...]

2024-09-13 01:01 UTC, bbonaby commented
Thanks for the feedback @PlagueHO. I updated the PR based on your comments. Thanks

2024-09-16 08:22 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

Thanks @bbonaby !

> Reviewed 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/279#-:-O6tvC-u4pK-lWKPc0WW:b-4n8irm)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @bbonaby)



<!-- Sent from Reviewable.io -->

2024-09-16 08:22 UTC, merged